version: 1.0.{build}
branches:
  only:
  - master
  - awsmulti
skip_tags: true
image: Visual Studio 2022
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: dotnet restore Ec2manager.sln
build:
  publish_wap: true
  verbosity: minimal
after_build:
- cmd: dotnet publish Ec2Manager\Ec2Manager.csproj --self-contained /p:PublishSingleFil=true
artifacts:
- path: '\Ec2Manager\bin\Release\net8.0\publish\'
  name: Ec2Manager
  type: WebDeployPackage
deploy:
- provider: GitHub
  tag: Ec2Manager-v$(appveyor_build_version)
  release: Ec2Manager-v$(appveyor_build_version)
  description: Ec2Manager-v$(appveyor_build_version)
  auth_token:
    secure: wstUVHRabe9ISotWIfasnM1/iL2vJha9FyHoy9BakcCM9FLDWKI2ivjGoPml/ZJQ